name: "Notificar Error"
description: Crea un issue detallando el error
title: "[SERVICIO y/o PROVEEDOR] Breve descripcion del error"
labels: []
assignees: []
body:
  - type: textarea
    id: error-desc
    attributes:
      label: Descripcion del error
      description: Detalles respecto al comportamiento del error, asi como el comportamiento esperado
      placeholder: |
        Al tratar de revisar una reserva de hoteles, aparece un error que detalla "No se pudo sincronizar a sistema de agencia...". 
        En su lugar, deberia actualizar la reserva
    validations:
      required: true
  - type: textarea
    id: error-steps
    attributes:
      label: Paso a paso para reproducir el error
      description: Detalles respecto al comportamiento del error
      placeholder: |
        1. Buscar en **Miami Y Sus Alrededores**, el **03/09/2021**, **2 adultos** 
        2. Hacer click en **Rodeway Inn Miami** 
        3. Reservar **1 King Bed**
        4. Ir al adm y revisar reserva"
    validations:
      required: true
  - type: textarea
    id: image
    attributes:
      label: Captura del error
      description: Pegar una captura que muestre el error
      placeholder: 👀
    validations:
      required: false
  - type: input
    id: link
    attributes:
      label: Link al error y/o Localizador
      description: Link de busqueda, link al adm y/o localizador de reserva
      placeholder: https://adm.ebooking.com.ar/bookings/detail/6112d49e4b463ea0a16070dc?purchaseGroupId=358722#heading_6112d49e4b463ea0a16070dc
    validations:
      required: true
  - type: input
    id: user-agent
    attributes:
      label: Plataforma
      description: "[¿Cual es mi plataforma?](https://www.google.com/search?q=whats+my+user+agent)"
      placeholder: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36
    validations:
      required: false
